jobs:
  - job: ChoreoAPIMBuild
    steps:
      - checkout: choreo-product-apim
        path: choreo-product-apim
        displayName: 'Checkout choreo-product-apim'

      - task: Cache@2
        displayName: 'Cache Maven artifacts'
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          path: $(MAVEN_CACHE_FOLDER)

      - task: Maven@3
        displayName: 'Build choreo-product-apim'
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'install'
          options: '-pl :org.wso2.choreo.am.integration.common.test.utils -am -Dmaven.test.skip=true $(MAVEN_OPTS)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          mavenVersionOption: 3.8.5

      - task: PublishPipelineArtifact@1
        displayName: 'Publish APIM artifacts'
        inputs:
          targetPath: '$(MAVEN_CACHE_FOLDER)/org/wso2/choreo/am'
          artifactName: 'APIMTestUtils'
