jobs:
  - job: ChoreoGlobalAdapterBuild
    dependsOn:
    - ChoreoAPIMBuild

    variables:
      SERVICE_BUS_NAMESPACE: '$(ASB_NAMESPACE_PREFIX)-$(Build.BuildId)'
      CONTAINER_REGISTRY: 'choreocontrolplane.azurecr.io'
      CHOREO_APIM_IMAGE: '$(CONTAINER_REGISTRY)/choreoipaas/choreo-product-apim'
      CHOREO_CONNECT_ADAPTER_IMAGE: '$(CONTAINER_REGISTRY)/choreoipaas/choreo-mgw-adapter'
      CHOREO_CONNECT_ENFORCER_IMAGE: '$(CONTAINER_REGISTRY)/choreoipaas/choreo-mgw-enforcer'
      CHOREO_CONNECT_ROUTER_IMAGE: '$(CONTAINER_REGISTRY)/choreoipaas/choreo-mgw-router'

    steps:
      - task: GoTool@0
        displayName: 'Install Go'
        inputs:
          version: '1.18.1'

      - script: |
          sudo apt update
          sudo apt install golint
        displayName: 'Install Golint'

      - task: Cache@2
        displayName: 'Cache Maven artifacts'
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          path: $(MAVEN_CACHE_FOLDER)

      - task: DownloadPipelineArtifact@2
        displayName: 'Download APIM dependencies'
        inputs:
          artifactName: 'APIMTestUtils'
          path: '$(MAVEN_CACHE_FOLDER)/org/wso2/choreo/am'

      - task: AzureCLI@2
        displayName: 'Create ASB'
        inputs:
          connectedServiceNameSelector: 'connectedServiceNameARM'
          connectedServiceNameARM: 'choreo-connect-ga-integration-test-rg'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az servicebus namespace create --resource-group $(RESOURCE_GROUP) --name $(SERVICE_BUS_NAMESPACE) --location eastus --sku Standard --subscription $(SUBSCRIPTION)
            az servicebus topic create --resource-group $(RESOURCE_GROUP) --namespace-name $(SERVICE_BUS_NAMESPACE) --name notification --subscription $(SUBSCRIPTION)
            az servicebus topic create --resource-group $(RESOURCE_GROUP) --namespace-name $(SERVICE_BUS_NAMESPACE) --name tokenrevocation --subscription $(SUBSCRIPTION)
            az servicebus topic create --resource-group $(RESOURCE_GROUP) --namespace-name $(SERVICE_BUS_NAMESPACE) --name billingcycleresetevent --subscription $(SUBSCRIPTION)
            az servicebus topic create --resource-group $(RESOURCE_GROUP) --namespace-name $(SERVICE_BUS_NAMESPACE) --name organizationpurge --subscription $(SUBSCRIPTION)
            az servicebus topic create --resource-group $(RESOURCE_GROUP) --namespace-name $(SERVICE_BUS_NAMESPACE) --name stepquotareset --subscription $(SUBSCRIPTION)
            az servicebus topic create --resource-group $(RESOURCE_GROUP) --namespace-name $(SERVICE_BUS_NAMESPACE) --name stepquotathreshold --subscription $(SUBSCRIPTION)
            az servicebus topic create --resource-group $(RESOURCE_GROUP) --namespace-name $(SERVICE_BUS_NAMESPACE) --name thresholdevent --subscription $(SUBSCRIPTION)
            ENDPOINT=$(az servicebus namespace authorization-rule keys list --resource-group $(RESOURCE_GROUP) --namespace-name $(SERVICE_BUS_NAMESPACE) --name RootManageSharedAccessKey --subscription $(SUBSCRIPTION) --query primaryConnectionString --output tsv)
            echo "##vso[task.setvariable variable=AZURE_CONNECTION_STRING]$ENDPOINT"

      - task: Docker@2
        displayName: 'ACR Login'
        inputs:
          command: login
          containerRegistry: 'wso2choreo-control-plane-acr'

      - script: |
          docker pull $(CHOREO_CONNECT_ADAPTER_IMAGE):latest
          docker pull $(CHOREO_CONNECT_ENFORCER_IMAGE):latest
          docker pull $(CHOREO_CONNECT_ROUTER_IMAGE):latest
          docker pull $(CHOREO_APIM_IMAGE):latest
        displayName: 'Pull APIM and MGW Docker images'

      - task: Maven@3
        displayName: 'Build Global Adapter'
        env:
          MONGODB_CONNECTION_STRING: $(MONGODB_CONNECTION_STRING)
          MONGODB_PRIVATE_KEY: $(MONGODB_PRIVATE_KEY)
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'clean install'
          options: '-P Release -s .maven/settings.xml $(MAVEN_OPTS)'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          mavenVersionOption: 3.8.5

      - task: AzureCLI@2
        displayName: 'Cleanup ASB'
        condition: always()
        inputs:
          connectedServiceNameSelector: 'connectedServiceNameARM'
          connectedServiceNameARM: 'choreo-connect-ga-integration-test-rg'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az servicebus namespace delete --resource-group $(RESOURCE_GROUP) --name $(SERVICE_BUS_NAMESPACE) --subscription $(SUBSCRIPTION)
