resources:
  repositories:
    - repository: choreo-product-apim
      type: github
      name: wso2-enterprise/choreo-product-apim
      endpoint: choreo-cicd
      ref: refs/heads/main

    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: choreo-cicd

trigger:
  branches:
    include:
      - refs/tags/v*

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'choreo-apim-ga-sb'

  - name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository

  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

  - name: CONTAINER_REGISTRY
    value: 'choreocontrolplane.azurecr.io'

jobs:
  - job: UnitTestsAndCoverage
    displayName: 'Unit Tests and Coverage'
    steps:
      - template: templates/run-unit-tests.yaml
  - template: templates/choreo-apim-test-util-build.yaml
  - template: templates/choreo-ga-build.yaml

  - job: ChoreoGlobalAdapterRelease
    dependsOn: BuildChoreoGlobalAdapter

    variables:
      GLOBAL_ADAPTER_REPOSITORY: choreoipaas/choreo-connect-global-adapter
      GLOBAL_ADAPTER_VERSION: ''

    steps:
      - script: |
          echo "##vso[task.setvariable variable=GLOBAL_ADAPTER_VERSION]$(cat pom.xml |
          grep -m1 "<version" | cut -d ">" -f2 | cut -d "<" -f1)"
        displayName: 'Retrieve Global adapter component versions'

      - task: DownloadPipelineArtifact@2
        displayName: 'Download GA Docker image'
        inputs:
            artifactName: 'GADockerImage'
            path: '$(Pipeline.Workspace)/docker'

      - script: |
          docker load -i $(Pipeline.Workspace)/docker/choreo-ga.tar
        displayName: 'Restore GA Docker image'

      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: 'wso2choreo-control-plane-acr'

      - script: |
          docker tag wso2/choreo-connect-global-adapter:$(GLOBAL_ADAPTER_VERSION) $(CONTAINER_REGISTRY)/$(GLOBAL_ADAPTER_REPOSITORY):$(Build.SourceBranchName)
        displayName: 'Tag Docker images to ACR repositories'

      - template: templates/trivy-docker-scan.yml
        parameters:
          repository: $(GLOBAL_ADAPTER_REPOSITORY)
          tag: $(Build.SourceBranchName)
          registry: $(CONTAINER_REGISTRY)

      - task: Docker@2
        inputs:
          command: push
          containerRegistry: 'wso2choreo-control-plane-acr'
          repository: $(GLOBAL_ADAPTER_REPOSITORY)
          tags: $(Build.SourceBranchName)
          displayName: 'Push Global Adapter Docker image'
