trigger:
  branches:
    include:
      - refs/tags/v*

pr: none

resources:
  repositories:
    - repository: choreo-connect-global-adapter
      type: github
      name: wso2-enterprise/choreo-connect-global-adapter
      endpoint: choreo-cicd
      ref: main
    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: choreo-cicd

jobs:
  - job: UnitTestsAndCoverage
    displayName: 'Unit Tests and Coverage'
    steps:
      - template: templates/run-tests.yaml
  - job: ChoreoGlobalAdapterRelease

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
      GLOBAL_ADAPTER_REPOSITORY: choreoipaas/choreo-connect-global-adapter
      MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
      MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
      IS_WORKFLOW_ENV: 'true'
      GLOBAL_ADAPTER_VERSION: ''
      GIT_COMMIT_ID: ''

    steps:

      - checkout: choreo-connect-global-adapter
        path: choreo-connect-global-adapter

      - task: DockerInstaller@0
        inputs:
          dockerVersion: 17.09.0-ce
          releaseType: stable
        displayName: Docker Installer

      - task: GoTool@0
        inputs:
          version: '1.16.13'
        displayName: Go Tool Installer

      - script: |
          sudo apt update
          sudo apt install golint
        displayName: Golint Installer
      - task: Cache@2
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(MAVEN_CACHE_FOLDER)
        displayName: Cache Maven local repo

      - script: |
          echo "##vso[task.setvariable variable=GLOBAL_ADAPTER_VERSION]$(cat $(Agent.BuildDirectory)/choreo-connect-global-adapter/pom.xml |
          grep -m1 "<version" | cut -d ">" -f2 | cut -d "<" -f1)"
        displayName: Retrieve Global adapter component versions
      - task: Maven@3
        inputs:
          mavenPomFile: '$(Agent.BuildDirectory)/choreo-connect-global-adapter/pom.xml'
          #goals: 'clean install -P Release -s .maven/settings.xml'
          goals: 'clean install -s .maven/settings.xml'
          options: '-Dmaven.test.skip=true'
          mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'

      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: 'wso2choreo-control-plane-acr'

      - script: |
          docker tag wso2/choreo-connect-global-adapter:$(GLOBAL_ADAPTER_VERSION) $(CONTAINER_REGISTRY)/$(GLOBAL_ADAPTER_REPOSITORY):$(Build.SourceBranchName)
        displayName: 'Tag docker images to ACR repositories'

      - template: templates/trivy-docker-scan.yml
        parameters:
          repository: $(GLOBAL_ADAPTER_REPOSITORY)
          tag: $(Build.SourceBranchName)
          registry: $(CONTAINER_REGISTRY)

      - task: Docker@2
        inputs:
          command: push
          containerRegistry: 'wso2choreo-control-plane-acr'
          repository: $(GLOBAL_ADAPTER_REPOSITORY)
          tags: $(Build.SourceBranchName)
          displayName: 'Push Global Adapter Docker image'
