name: Global Adapter build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3        
    - name: Build with Maven
      run: |
        export PATH="${HOME}/go/bin:${PATH}"
        mvn clean install -s .maven/settings.xml
