# The configuration file for mgw

[keystore]
  certPath = "$env{MGW_HOME}/security/keystore/global-adapter.pem"
  keyPath = "$env{MGW_HOME}/security/keystore/global-adapter.key"
  
[truststore]
  location = "$env{MGW_HOME}/security/truststore"
	
# Control plane's connection details
[controlPlane]
  serviceUrl = "https://apim:9443/"
  username="admin"
  password="$env{cp_admin_pwd}"
  environmentLabels = ["Default", "Prod"]
  #retryInterval = 5
  #skipSSLVerification=true
  # Message broker connection URL of the control plane
  [controlPlane.brokerConnectionParameters]
    eventListeningEndpoints = ["amqp://admin:$env{cp_admin_pwd}@apim:5672?retries='10'&connectdelay='30'"]
  [controlPlane.jmsConnectionParameters]
      eventListeningEndpoints = ["amqp://admin:$env{cp_admin_pwd}@apim:5672?retries='10'&connectdelay='30'"]

[server]
  host = '0.0.0.0'
  port = '9843'
  partitionSize = 1000
  partitionThreshold = 0.9
  [[server.users]]
    username = 'admin'
    password = '$env{ga_admin_pwd}'

[database]
  name = 'choreo-mssql'
  username = 'db_user'
  password = '$env{ga_db_pwd}'
  host = 'mssql-db'
  port = 1433
  validationQuery = 'select 1'
  [database.pooloptions]
  maxActive = 50
  maxWait = 60000
  testOnBorrow = true
  validationInterval = 30000
  defaultAutoCommit = true

[redisServer]
  host = 'redis-host-url'
  port = 6380
  password = '$env{redis_host_pwd}'
  clientName = 'global-adapter'
  databaseIndex = 2
  connectionPoolSize = 3
  maxRetryCount = 10
